@startuml
class eva2_practica5_ejemplo_herencia.EVA2_Practica5_EJEMPLO_HERENCIA
class eva2_practica5_ejemplo_herencia.Empleado
class eva2_practica5_ejemplo_herencia.Persona
eva2_practica5_ejemplo_herencia.Empleado --|> eva2_practica5_ejemplo_herencia.Persona
@enduml